name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# custom workflow level env variables:
env: 
  param1: param1
  param2: param2


jobs:
  first-job:
    runs-on: ubuntu-latest

    # custom job level env variables:
    env: 
      job-param1: job-param1

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a one-line script
        run: echo param1 is ${{env.param1}} and job-param1 is ${{env.job-param1}}
