name: Second

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - shell: bash
        run: |
          echo Hello, from bash
      
      - name: Run node
        run: node test.js 