name: Second

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - shell: bash
        run: |
          echo Hello, from bash
      
      - name: Run node
        run: node test.js 

      - name: List files
        run: ls 

      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: output

  second-job:
    runs-on: ubuntu-latest

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts
    
      - name: List files
        run: ls output