name: Third

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Hello step
      run: echo Hello

    - name: GitHub Cli
      run: |
        gh issue create --title "Issue ${{github.sha}} created" --body "Body"
